:experimental:
ifdef::env-github[]
:icons:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:imagesdir: imgs/

. After finished rebooting, open your terminal emulator, likely "Terminal" or "Konsole".
. Run `# sudo mkinitcpio -P`.
. Reboot.

NOTE: Anything to do with DKMS/initramfs/modprobe currently isn't called directly by Dux. +
It will be in Dux's C++ rewrite.

== Terminal commands
* Package manager:
** `$ paru -Syu`: Update all non-AUR and AUR packages
** `# pacman -Syu`: Update all non-AUR packages

== Graphical environments
NOTE: Win/Super/kbd:[Meta]/Mod4 are the same key, it's usually between kbd:[LCtrl] and kbd:[LAlt].

* Open the help dialog (shows keybinds): kbd:[Meta] + kbd:[LShift] + kbd:[a] 

== Tips 
* If more performance is desired, then install `linux-xanmod-edge` (latest) or `linux-xanmod-lts` (Long-Term Support) from the AUR.
** NOTE: For NVIDIA, install `nvidia-dkms`. For 470 drivers it'd be `nvidia-470xx-dkms`; 390 drivers are `nvidia-390xx-dkms`.
** Run `$ gpg2 --locate-keys torvalds@kernel.org gregkh@kernel.org` before attempting an install; note that your PC has to compile the kernel, so it will take around 10 minutes or up to hours depending on the CPU's speed.

* Changing icon colors:
** Example: `# papirus-folders -C yaru`
** `# papirus-folders -l`: List all available colors.

== Warnings
* Avoid doing the following for Btrfs:
** Enabling quotas
** Deleting subvolumes

___
*If you have issues, please read => link:potential_fixes.adoc[potential_fixes.adoc]*