:experimental:
ifdef::env-github[]
:icons:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:imagesdir: imgs/

NOTE: Skip to link:0.1_start.adoc[0.1_start.adoc] for installation.

== Requirements
* A x86_64 processor/CPU; arm64 and others aren't officially supported, but might work fine.
* link:https://archive.is/QwLMB[Disable UEFI Secure Boot]
** If convincing is needed, link:https://github.com/pbatard/rufus/wiki/FAQ#Why_do_I_need_to_disable_Secure_Boot_to_use_UEFINTFS[read this].
* A >=3GB USB to flash a Manjaro ISO on.


== Goals

[%collapsible]
====
* *Resilience*
** A read-only Btrfs snapshot is made as a means of backup. Scripts that can be ran outside of `dux_installer.sh` backup every file/folder modified individually.
** The built-in ricing is ensured to not cause breakages in future updates for both GNOME and KDE.
** No third-party Pacman (package) repositories are ever used.
** Official Manjaro ISOs are used, they're a solid foundation, and they have many maintainers instead of one.

* *Stability*
** Dux has a unique take on "ricing" (customization) by avoiding the following:
*** Stringing together a bunch of different software by different developers, likely also dealing with conflicting opinions.
*** Pushing you towards having to resort to manpages/manuals and configuration files, instead of trying out changes in a concise environment (what the developer exposes in a GUI, example: KDE's System Settings).

* *KISS*
** Dux heavily benefits from simplicity for both the user and the programmer.
*** This simplicity makes way for extending more time into what matters more, like having a program to easily manage and pick from known good configurations of software.

** If there's a better way of doing something which leads into additional simplicity for the big picture, that should be pursued as well.

* To be forked.
** Want to contribute but disagree with something in link:CONTRIBUTING.adoc[CONTRIBUTING.adoc]? No problem, Dux has been fully intended to be easy for you to make the Manjaro customizer you want.
*** Credit (a link to Dux in the README) should be given so others can find their way back to here, but it's optional (despite what the license says).
**** I use the strongest open-source license due to the legal protections it grants me in my home country of the United States, it'd be foolish not to do so.

== Why Manjaro instead of Arch Linux (as was the case in link:https://github.com/nermur/dux-legacy[dux-legacy])
* Many AUR packages are officially packaged and tested by Manjaro developers.
** Makes for a more stable base, and drastically reduces the installation time of Dux.
* Manjaro dodges some severe problems Arch has seemingly every few months by not constantly rolling out updates; updates are done around every 2 weeks in large chunks on the 'stable' repos, but you can use 'testing' repos to get the same rolling experience Arch Linux has.
* Includes software such as Pamac which greatly increase the usability of Arch for those that don't wish to touch the terminal.
** Even if the terminal gets used frequently, it's a useful utility to have an easier time tracking down changes.
* Dux is by one man, and there won't be others with direct access to this repo for trust/security reasons.
** I have many different interests, and not enough time to juggle between them all.

====


== Notable features installed by Dux
* `KDE` and `GNOME` desktop environments having an equal level of support/testing.

* Support for old to new NVIDIA GPUs.
** Nouveau drivers can optionally be tweaked to be relatively stable without sacrificing speed (on a 650 Ti), which by default was very unstable.

* Sharp and clear font rendering for low-DPI and high-DPI displays to emphasize readability.
** Websites or software that use Microsoft's fonts also look as intended.

* `zRAM`
** Memory compression used to stop relying on a disk swap file that reduces the life-span of disks, and to avoid heavy I/O usage that would slow the system down noticeably.

* `GameMode`
** Allows for a process to request temporary disabling of power-saving features for extra performance, mainly used by Lutris for video games.

* `PipeWire` tweaks
** For consistently low latency audio, making Bluetooth audio devices more enjoyable to use, and aid with fast rhythm games such as osu! and StepMania.
** If `PulseAudio` is installed, it will be replaced with `PipeWire`.

* Rootless `Xorg` display server
** Less memory usage and increased security; not used for NVIDIA GPUs however, as it breaks its overclocking capabilities.

* `BBRv2`: A TCP congestion control for lower bufferbloat; read about its positive effects on download/upload speeds and latency link:https://archive.ph/l0zc8[here].
** NOTE: qdisc is left at default, rather than the CAKE qdisc being used: +
https://github.com/systemd/systemd/issues/9725#issuecomment-564872011

* `Btrfs` is used to: 
** Compress data in real-time without noticeable performance impacts, reducing write amplification (increases longevity of disks by lowering disk usage), and increasing read speeds on slow disks.
** Have high-performance and deduplicated "snapshots" (backups) of key areas, which turns Manjaro updates breaking software into a small nuisance, as it's very quick and easy to restore to a previous snapshot.
** Allow for an easier data recovery if a disk gets damaged and/or starts to have bad sectors.
** To once a month automatically check (Scrub) over all filesystem data and metadata and verifying the checksums, repairing damage if present and possible.

* `I/O scheduling changes`
** `mq-deadline` for SSDs and eMMCs (flash/USB disks/SD cards), `bfq` for spinning disks (HDDs). +
This makes these types of storage highly responsive to your inputs.

* `irqbalance`
** Manages IRQ interrupts more efficiently by being more aware of the current environment. One example is offloading IRQ interrupts to CPU affinities which have the lowest load on them. Another example is respecting VMs having their CPU affinities isolated, meaning irqbalance will offload the IRQ interrupts to CPU affinities that aren't isolated.

* `Flatpak`
** Visual inconsistencies with Flatpaks are mostly fixed.

* `thermald`
** Provides a large performance boost for some Intel laptops, with no observable downsides for other hardware combinations.
** https://www.phoronix.com/scan.php?page=article&item=intel-thermald-tgl&num=2

* Disabled `Baloo` "full-text" indexer
** It's preferred to load files on demand then cache their thumbnails; a simpler approach that works reliably and without performance issues.
** `Baloo` has a link:https://bugs.kde.org/show_bug.cgi?id=402154[long-standing bug] related to usage of Btrfs subvolumes (which we use), that greatly impacts disk usage and overall system performance.
*** Even without this bug, file indexers daemons like `Baloo` won't be used as their design is conceptually over-complicated, and will always be problematic.

* No `systemd-oomd` and no `earlyoom`
** Let the Linux kernel handle OOM (out of memory) situations, since our usage of `zRAM` makes Linux handle its OOM killer much more efficiently than before (still not good however).
*** Likely from link:https://www.phoronix.com/scan.php?page=news_item&px=Linux-MGLRU-v9-Promising[Linux kernel 5.20 and beyond] there'd be substantial improvements to OOM situations, that make `systemd-oomd` and `earlyoom` superficial.

* `nftables`
** https://firewalld.org/2018/07/nftables-backend

* `NetworkManager` defaulting to `iwd` for its WiFi backend, for increased network stability and performance.

* `dbus-broker`
** Replaces `dbus-daemon` for the system bus, as it's faster and more stable.


== Other Arch Linux installers

NOTE: These I think are decent for what they are. Some of the code and ideas in Dux have been inspired by what they've done for their projects.

. https://www.arcolinux.info/ or https://arcolinux.com/
** There are many good learning resources on Arch Linux provided by here too.
. https://endeavouros.com/
. https://anarchyinstaller.gitlab.io/
. https://github.com/classy-giraffe/easy-arch
. https://github.com/ChrisTitusTech/ArchTitus
. https://garudalinux.org/

___
=> link:0.1_start.adoc[0.1_start.adoc]